# This file was generated by GoReleaser. DO NOT EDIT.
cask "jp" do
  name "jp"
  desc "JSON stream processor and transformation tool"
  homepage "https://github.com/arnodel/jsonstream"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jp"

  on_macos do
    on_intel do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_macOS_amd64.tar.gz"
      sha256 "4af90ae5e1063fb58848b6bda3223e6a1d5d18a94c66245281adb7db681fce44"
    end
    on_arm do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_macOS_arm64.tar.gz"
      sha256 "cf0446ea0f137242ebfce1bcc4844f6c5013f111cc69d47b5159e7d867710ef6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_linux_amd64.tar.gz"
      sha256 "80a790f07c16749e9f1b401c9f04c3fd5ec1969b625b883ea3f4e0d79d4b8aa3"
    end
    on_arm do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_linux_arm64.tar.gz"
      sha256 "16d64fbe9aedae21ba8ba69ee30b82c004b79dedf6feddaa1fec51e4a4c33a6d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jp"]
    end
  end

  # No zap stanza required
end
