# This file was generated by GoReleaser. DO NOT EDIT.
cask "jp" do
  name "jp"
  desc "JSON stream processor and transformation tool"
  homepage "https://github.com/arnodel/jsonstream"
  version "0.1.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jp"

  on_macos do
    on_intel do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_macOS_amd64.tar.gz"
      sha256 "f91af74b4e9079b1eb624cf8e116982f66d269143d7632e83882551c77f04e80"
    end
    on_arm do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_macOS_arm64.tar.gz"
      sha256 "b6614030869270b801ea87021572a4f6bb4c714b672293b126a1b1cd94b9c2bb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_linux_amd64.tar.gz"
      sha256 "6e7b9be2558fa8a28a8bfe49340fbdfbf04dc8ca10702b50ce6e3bdfd9ac21a4"
    end
    on_arm do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_linux_arm64.tar.gz"
      sha256 "4f05cc9afd658111c14668342291bacb0242452c222bba5a3e76940144b6f251"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jp"]
    end
  end

  # No zap stanza required
end
