# This file was generated by GoReleaser. DO NOT EDIT.
cask "jp" do
  name "jp"
  desc "JSON stream processor and transformation tool"
  homepage "https://github.com/arnodel/jsonstream"
  version "0.1.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jp"

  on_macos do
    on_intel do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_macOS_amd64.tar.gz"
      sha256 "9411b7fb375fee26ed853b452ff88c19a3aa3e77212a6ca8e2875941a439e74c"
    end
    on_arm do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_macOS_arm64.tar.gz"
      sha256 "89c142540b89b5a34b913a9c7bff1347dc821d3ded167935f1f9b9eda8accd74"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_linux_amd64.tar.gz"
      sha256 "c15ef8d2f6519526c12c4f7be55440b4aa80edc0121f2e287d15b648e5a39600"
    end
    on_arm do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_linux_arm64.tar.gz"
      sha256 "f6ea2bfd6666e5a97e81b0fca8023e4088127de7e9caca88544ea2776fde26dc"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jp"]
    end
  end

  # No zap stanza required
end
