# This file was generated by GoReleaser. DO NOT EDIT.
cask "jsonstream" do
  name "jsonstream"
  desc "JSON stream processor and transformation tool"
  homepage "https://github.com/arnodel/jsonstream"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jp"

  on_macos do
    on_intel do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_macOS_amd64.tar.gz"
      sha256 "5c643ce1fa75051cb8227f603b72a45f82cc6dc47907759fb06e42a9106a5d5a"
    end
    on_arm do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_macOS_arm64.tar.gz"
      sha256 "de499ac5bbb612d7f9222a09b4109cc13105e1dbc9ea207b4cca9427e8ce4245"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_linux_amd64.tar.gz"
      sha256 "41f763641424fe97d1297a38aa4d05cfad88d04ac5dc6a53e4c39cb3a30fa072"
    end
    on_arm do
      url "https://github.com/arnodel/jsonstream/releases/download/v#{version}/jsonstream_#{version}_linux_arm64.tar.gz"
      sha256 "54b50ac24bb6d4ad7989a51b520d68734dbed2c9210fcd306808e0fdf3c067f2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jp"]
    end
  end

  # No zap stanza required
end
