# This file was generated by GoReleaser. DO NOT EDIT.
cask "whynot" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "873d9d470e375fe530cdc07fb22b45158ce121dc6149756d6b499b7360396c08"
      url "https://github.com/arnodel/whynot/releases/download/v#{version}/whynot_#{version}_macOS_arm64.zip"
    end
    on_intel do
      sha256 "52977662de2bf5380f2658cddc4dde911b2ee85e7b0c3416df4fe1097dbd1bd7"
      url "https://github.com/arnodel/whynot/releases/download/v#{version}/whynot_#{version}_macOS_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "2042dae5199d7b7bf0e192f5250a1bcf22dd11e22573a12d4c9c5ffdd3f76f31"
      url "https://github.com/arnodel/whynot/releases/download/v#{version}/whynot_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b59b0b790d7d9f4dcd469305af82f524993d6c8fcc98e5a85760f7f505bf0780"
      url "https://github.com/arnodel/whynot/releases/download/v#{version}/whynot_#{version}_linux_amd64.tar.gz"
    end
  end

  name "whynot"
  desc "A Markdown file renderer for Ebitengine games"
  homepage "https://github.com/arnodel/whynot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whynot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whynot"]
    end
  end

  # No zap stanza required
end
