# This file was generated by GoReleaser. DO NOT EDIT.
cask "whynot" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "9e57b78a7536fe8a0aa9ce3f95cb4b15c421556e48e31083749d3c7c8055879f"
      url "https://github.com/arnodel/whynot/releases/download/v#{version}/whynot_#{version}_macOS_arm64.zip"
    end
    on_intel do
      sha256 "df0fe62a52fa60aae24a2a3f63d83cc3cc1b169c516e35ddddf22d2332200bc1"
      url "https://github.com/arnodel/whynot/releases/download/v#{version}/whynot_#{version}_macOS_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "783f196fcc73346e032b6925ef42cb36ec206c1accf6bafdea5602b7396cbea0"
      url "https://github.com/arnodel/whynot/releases/download/v#{version}/whynot_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "94513cb26df9e346c047fe12da7ad59f6723aa85a93041e6e6ed8af88952f471"
      url "https://github.com/arnodel/whynot/releases/download/v#{version}/whynot_#{version}_linux_amd64.tar.gz"
    end
  end

  name "whynot"
  desc "A Markdown file renderer for Ebitengine games"
  homepage "https://github.com/arnodel/whynot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whynot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whynot"]
    end
  end

  # No zap stanza required
end
