# This file was generated by GoReleaser. DO NOT EDIT.
cask "whynot" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "454e7f9639bfc448d53f35483631564f34f8b6c1325b3589ec7920ba7d657419"
      url "https://github.com/arnodel/whynot/releases/download/v#{version}/whynot_#{version}_macOS_arm64.zip"
    end
    on_intel do
      sha256 "acca2e150416fd3ea10fb960d99dceb6c54f91b3355c5749ed410fb444c09113"
      url "https://github.com/arnodel/whynot/releases/download/v#{version}/whynot_#{version}_macOS_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "549af09da695a530019e23cd9886014c148e46ada6987ea17179ed9ce2bc21d4"
      url "https://github.com/arnodel/whynot/releases/download/v#{version}/whynot_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c03c789cdd489181a684ad04f3cbb5f3a519622c1bbb694b9c0cdb8f41e71ca5"
      url "https://github.com/arnodel/whynot/releases/download/v#{version}/whynot_#{version}_linux_amd64.tar.gz"
    end
  end

  name "whynot"
  desc "A Markdown file renderer for Ebitengine games"
  homepage "https://github.com/arnodel/whynot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "whynot"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/whynot"]
    end
  end

  # No zap stanza required
end
